version: "2"
name: flink-rp-minio
services:
  flink:
    container_name: flink
    build:
      context: ./flink
      dockerfile: Dockerfile
      args:
        INSTALL_MAVEN: true
        INSTALL_GRADLE: false
        INSTALL_NODE: false
        NODE_VERSION: lts/*
        AWS_ACCESS_KEY_ID: minio
        AWS_SECRET_ACCESS_KEY: minio123
        #AWS_REGION: us-east-1
        #AWS_DEFAULT_REGION: us-east-1
        S3_ENDPOINT: http://minio:9000
        S3_PATH_STYLE_ACCESS: true
    volumes:
    - ..:/workspaces:cached
    #ports:
    #  - 8081:8081
  redpanda:
      container_name: redpanda
      image: docker.redpanda.com/vectorized/redpanda:v23.1.2
      command:
        - redpanda start
        - --smp 1
        - --overprovisioned
        - --node-id 0
        - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
        - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
        - --pandaproxy-addr 0.0.0.0:8082
        - --advertise-pandaproxy-addr localhost:8082
      ports:
        - 8091:8081
        - 8082:8082
        - 9092:9092
        - 9644:9644
        - 29092:29092
  console:
    container_name: console-rp
    image: docker.redpanda.com/vectorized/console:latest
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:29092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
        connect:
          enabled: true
          clusters:
            - name: local-connect-cluster
              url: http://connect:8083
    ports:
      - 8080:8080
    depends_on:
      - redpanda
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}